max_obstacle_height: 0.60  
obstacle_range: 2.5
raytrace_range: 3.0

robot_radius: 0.4509

inflation_radius: 0.5  
cost_scaling_factor: 5 


map_type: costmap
transform_tolerance: 5 # seconds


origin_z: 0.0
z_resolution: 0.2
z_voxels: 2
publish_voxel_map: false

observation_sources: scan


scan: {data_type: LaserScan, topic: /scan, marking: true, clearing: true, min_obstacle_height: 0.0, max_obstacle_height: 3}

